categories: 'historical-data'
mode: 'country'
years: 2021 # can be a list or an int
currency: 'EUR'
historical_items: ['1 Pair of Jeans (Levis 501 Or Similar)', 'Banana (1kg)'] # can be a list or a string

# optional parameter (can be a list or a string)
countries: ['China', 'France', 'United States']