categories: 'historical-data'
mode: 'country'
years: [2019, 2020, 2021, 2022]
countries: ['Brazil', 'Italy']
historical_items: ['1 Pair of Jeans (Levis 501 Or Similar)', 'Loaf of Fresh White Bread (500g)']
currency: 'EUR'