categories: ['cost-of-living', 'pollution', 'traffic'] # this can also be a list
mode: 'city'
years: [2023, 2024, 2025] # can be a list or an int
cities: ['Lyon', 'Milan', 'Brussels'] # can be a list or a string