from typing import List, Literal, Union, Optional

from pydantic import BaseModel

from ..core.utils import partial_model


VALID_YEARS = Literal[
    2012,
    "2012-mid",
    2013,
    "2013-mid",
    2014,
    "2014-mid",
    2015,
    "2015-mid",
    2016,
    "2016-mid",
    2017,
    "2017-mid",
    2018,
    "2018-mid",
    2019,
    "2019-mid",
    2020,
    "2020-mid",
    2021,
    "2021-mid",
    2022,
    "2022-mid",
    2023,
    "2023-mid",
    2024,
    "2024-mid",
    2025,
]

VALID_CATEGORIES = Literal[
    "cost-of-living",
    "quality-of-life",
    "crime",
    "health-care",
    "pollution",
    "traffic",
    "property-investment",
    "historical-data",
]

VALID_MODES = Literal["country", "city"]

VALID_REGIONS = Literal["Africa", "America", "Asia", "Europe", "Oceania"]

VALID_CURRENCIES = Literal[
    "AED",
    "AFN",
    "ALL",
    "AMD",
    "ANG",
    "AOA",
    "AUD",
    "AWG",
    "AZN",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BHD",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BRL",
    "BSD",
    "BTN",
    "BWP",
    "BYN",
    "BZD",
    "CAD",
    "CDF",
    "CHF",
    "CLF",
    "CLP",
    "CNH",
    "CNY",
    "COP",
    "CRC",
    "CUC",
    "CVE",
    "CZK",
    "DJF",
    "DKK",
    "DOP",
    "EGP",
    "ERN",
    "EUR",
    "FJD",
    "FKP",
    "GBP",
    "GEL",
    "GGP",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "HKD",
    "HNL",
    "HRK",
    "HTG",
    "HUF",
    "IDR",
    "ILS",
    "IMP",
    "INR",
    "IQD",
    "IRR",
    "ISK",
    "JEP",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KGS",
    "KHR",
    "KMF",
    "KPW",
    "KRW",
    "KWD",
    "KYD",
    "KZT",
    "LAK",
    "LKR",
    "LRD",
    "LSL",
    "LYD",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MNT",
    "MOP",
    "MRU",
    "MUR",
    "MVR",
    "MXN",
    "MYR",
    "MZN",
    "NAD",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "OMR",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "RWF",
    "SAR",
    "SBD",
    "SCR",
    "SDG",
    "SEK",
    "SGD",
    "SHP",
    "SLL",
    "SOS",
    "SRD",
    "STD",
    "STN",
    "SVC",
    "SYP",
    "SZL",
    "THB",
    "TJS",
    "TMT",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "TZS",
    "UAH",
    "UGX",
    "USD",
    "UYU",
    "UZS",
    "VES",
    "VND",
    "VUV",
    "WST",
    "XAF",
    "XAG",
    "XCD",
    "XDR",
    "XOF",
    "XPF",
    "YER",
    "ZAR",
    "ZMW",
    "ZWL",
]

VALID_COUNTRIES = Literal[
    "Afghanistan",
    "Aland Islands",
    "Albania",
    "Alderney",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua And Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia And Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle Of Man",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo (Disputed Territory)",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norfolk Island",
    "North Korea",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic Of Congo",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Helena",
    "Saint Kitts And Nevis",
    "Saint Lucia",
    "Saint Vincent And The Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome And Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad And Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks And Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Us Virgin Islands",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

VALID_ITEMS = Literal[
    "Price per Square Meter to Buy Apartment Outside of Centre",
    "Price per Square Meter to Buy Apartment in City Centre",
    "International Primary School, Yearly for 1 Child",
    "Preschool (or Kindergarten), Full Day, Private, Monthly for 1 Child",
    "1 Pair of Jeans (Levis 501 Or Similar)",
    "1 Pair of Men Leather Business Shoes",
    "1 Pair of Nike Running Shoes (Mid-Range)",
    "1 Summer Dress in a Chain Store (Zara, H&M, ...)",
    "Apples (1kg)",
    "Banana (1kg)",
    "Beef Round (1kg) (or Equivalent Back Leg Red Meat)",
    "Bottle of Wine (Mid-Range)",
    "Chicken Fillets (1kg)",
    "Cigarettes 20 Pack (Marlboro)",
    "Domestic Beer (0.5 liter bottle)",
    "Eggs (regular) (12)",
    "Markets: Imported Beer (0.33 liter bottle)",
    "Lettuce (1 head)",
    "Loaf of Fresh White Bread (500g)",
    "Local Cheese (1kg)",
    "Milk (regular), (1 liter)",
    "Onion (1kg)",
    "Oranges (1kg)",
    "Potato (1kg)",
    "Rice (white), (1kg)",
    "Tomato (1kg)",
    "Water (1.5 liter bottle)",
    "Apartment (1 bedroom) Outside of Centre",
    "Apartment (1 bedroom) in City Centre",
    "Apartment (3 bedrooms) Outside of Centre",
    "Apartment (3 bedrooms) in City Centre",
    "Cappuccino (regular)",
    "Coke/Pepsi (0.33 liter bottle)",
    "Domestic Beer (0.5 liter draught)",
    "Restaurants: Imported Beer (0.33 liter bottle)",
    "McMeal at McDonalds (or Equivalent Combo Meal)",
    "Meal for 2 People, Mid-range Restaurant, Three-course",
    "Meal, Inexpensive Restaurant",
    "Water (0.33 liter bottle)",
    "Average Monthly Net Salary (After Tax)",
    "Mortgage Interest Rate in Percentages (%), Yearly, for 20 Years Fixed-Rate",
    "Cinema, International Release, 1 Seat",
    "Fitness Club, Monthly Fee for 1 Adult",
    "Tennis Court Rent (1 Hour on Weekend)",
    "Gasoline (1 liter)",
    "Monthly Pass (Regular Price)",
    "One-way Ticket (Local Transport)",
    "Taxi 1hour Waiting (Normal Tariff)",
    "Taxi 1km (Normal Tariff)",
    "Taxi Start (Normal Tariff)",
    "Toyota Corolla Sedan 1.6l 97kW Comfort (Or Equivalent New Car)",
    "Volkswagen Golf 1.4 90 KW Trendline (Or Equivalent New Car)",
    "Basic (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment",
    "Internet (60 Mbps or More, Unlimited Data, Cable/ADSL)",
    "Mobile Phone Monthly Plan with Calls and 10GB+ Data",
]


@partial_model
class Input(BaseModel):
    """
    Input schema.
    """

    categories: Union[VALID_CATEGORIES, List[VALID_CATEGORIES]]
    mode: VALID_MODES
    years: Union[VALID_YEARS, List[VALID_YEARS]]
    regions: Union[VALID_REGIONS, List[VALID_REGIONS]]
    currency: VALID_CURRENCIES
    countries: Union[VALID_COUNTRIES, List[VALID_COUNTRIES]]
    historical_items: Union[VALID_ITEMS, List[VALID_ITEMS]]
    cities: Union[str, List[str]]
